### ISSUE TITLE
.math shouldnt be using eval for math

### ISSUE THREAD

**Issue by RandomVersion** [Code-Theft-Auto/sockeyPy#2]
Using eval is very dangerous as it could lead to command execution and more.
example:
```.math "__import__('os').system('reboot')"```
this will call the reboot command causing the system to reboot, you can also pop a shell using a space-less eval payload.

**Comment by RandomVersion** [comment]
and yes its working on the production bot

**Comment by RandomVersion** [comment]
![image](https://user-images.githubusercontent.com/78416873/166230960-1e5f375a-a15c-423e-8071-76ff38119dbf.png)

**Comment by BananaBoii600** [comment]
alright thanks, we will make sure to fix it

**Comment by DevER-M** [comment]
fixed it @RandomVersion

**Comment by DevER-M** [comment]
im closing this issue now :)
